# Generated by Django 4.2.3 on 2024-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaxi', '0017_rename_fruits_inquiry_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='shiji_no',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='possibility',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='reuse',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='purpose',
            field=models.CharField(max_length=999),
        ),
    ]
