# Generated by Django 4.2.3 on 2024-08-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caretaxi', '0018_rename_shiji_no_inquiry_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='name',
            new_name='carmodel',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='design_image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='purpose',
            new_name='siteurl',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='shiji_name',
            new_name='tel',
        ),
    ]
