# Generated by Django 4.2.3 on 2024-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaxi', '0019_rename_name_inquiry_carmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='business_name',
            field=models.CharField(default='未設定', max_length=999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='features',
            field=models.CharField(default='未設定', max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='carmodel',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='genres',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='location',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='tel',
            field=models.CharField(max_length=16),
        ),
    ]
