# Generated by Django 4.2.3 on 2024-08-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaxi', '0021_registration_delete_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='postal_code',
            field=models.CharField(default='未設定', max_length=8, verbose_name='郵便番号'),
            preserve_default=False,
        ),
    ]
