# Generated by Django 4.2.3 on 2024-08-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaxi', '0023_contactmodel_delete_emailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='onamae',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name_kana',
            field=models.CharField(default='未設定', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='business_name',
            field=models.CharField(default='未設定', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='postal_code',
            field=models.CharField(default='未設定', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='tel',
            field=models.CharField(max_length=15),
        ),
    ]
