# Generated by Django 4.2.3 on 2024-08-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caretaxi', '0024_rename_onamae_contactmodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='address',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='location',
            field=models.CharField(default='未設定', max_length=255),
            preserve_default=False,
        ),
    ]
